### ISSUE TITLE
bundleconfig.json comments not removed when converting to gulp

### ISSUE THREAD

**Issue by scottaddie** [madskristensen/BundlerMinifier#161]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- This extension: 2.1.258

### Description
The comments included in the default `bundleconfig.json` file aren't being removed when selecting the **Convert to Gulp** context menu item.

### Steps to recreate
1. Create a new ASP.NET Core Web Application (.NET Core) with the "StarterWeb" project template
2. Right-click the `bundleconfig.json` file in Solution Explorer and choose **Bundler & Minifier** --> **Convert to Gulp**
3. View the Task Runner Explorer window
4. View the Output window's Task Runner Explorer pane and notice an error similar to the following:

> Failed to run "C:\working_folder\WebApplication2\src\WebApplication2\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:427
    throw err;
    ^
SyntaxError: C:\working_folder\WebApplication2\src\WebApplication2\bundleconfig.json: Unexpected token /
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\working_folder\WebApplication2\src\WebApplication2\gulpfile.js:10:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

### Current behavior
When the `bundleconfig.json` file is imported via the **require** in `gulpfile.js`, the comments cause this issue. This issue is actually already documented in the generated `gulpfile.js`:
```javascript
bundleconfig = require("./bundleconfig.json"); // make sure bundleconfig.json doesn't contain any comments
```

### Expected behavior
Upon selecting **Bundler & Minifier** --> **Convert to Gulp**, any comments in `bundleconfig.json` should be stripped.

**Comment by scottaddie** [comment]
The fix for this has been merged.
