### ISSUE TITLE
using wildcard 

### ISSUE THREAD

**Issue by tajamal** [madskristensen/BundlerMinifier#192]
### Installed product versions
- Visual Studio: 2015 Professional, Version 14.0.25425.01 Update 3
- This extension: 2.2.293

### Description
Adding files using wildcard 

### Steps to recreate
1. inlude js files using wildcard 
2. add "/assets/*.js" 

### Current behavior
```
> Bundler & Minifier 
> There is an error in the bundlerconfig.json file. This could be due to a change in the format after extension was updated. 
```

### Expected behavior
This should bundle and minify but it doesn't.

**Comment by madskristensen** [comment]
It's likely that you start the file with a forward slash. Try to remove it and see  if that helps

**Comment by tajamal** [comment]
I figured it out when the problem occurs. Its good within the project and works fine. 

Though I have a nuget package "SharedCode" with js files, however when I update my project with new package  "Bundler & minifier" show these errors. The error only occurs when I have js files with wildcard in a path (see bundleconfig.json below). 

I noticed the path "C:\projects" in the error below, it doesn't exist on my  C drive, but that I assume is error in the code of "Bundler & minifier"? 

```
10-10-2016 09:28:28: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\web\mypro\assets\scripts\SharedCode\footer'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at BundlerMinifier.Bundle.GetAbsoluteInputFiles(Boolean notifyOnPatternMiss) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\Bundle.cs:line 96
   at BundlerMinifier.BundleFileProcessor.SourceFileChanged(String bundleFile, String sourceFile) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 65
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass11_0.<SourceFileChanged>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 169
10-10-2016 09:28:56: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\web\mypro\assets\scripts\SharedCode\footer'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at BundlerMinifier.Bundle.GetAbsoluteInputFiles(Boolean notifyOnPatternMiss) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\Bundle.cs:line 96
   at BundlerMinifier.BundleFileProcessor.SourceFileChanged(String bundleFile, String sourceFile) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 65
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass11_0.<SourceFileChanged>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 169

```
bundleconfig.json:

```
[
  {
    "outputFileName": "public/scripts/app-header.js",
    "inputFiles": [
      "assets/scripts/SharedCode/jquery-2.1.4.js",
      "assets/scripts/SharedCode/jquery-ui-1.11.4.min.js",      
      "assets/scripts/SharedCode/menuFunctions.js",
      "assets/scripts/SharedCode/header/*.js",
      "assets/scripts/SharedCode/header/*.min.js",
      "assets/scripts/app/header/*.js",
      "assets/scripts/app/header/*.min.js"
    ],
    "minify": {
      "enabled": true,
      "preserveImportantComments": true
    }
  },
  {
    "outputFileName": "public/scripts/app-footer.js",
    "inputFiles": [
        "assets/scripts/SharedCode/slimmage.settings.min.js",
        "assets/scripts/SharedCode/slimmage.min.js",
        "assets/scripts/SharedCode/jquery.unobtrusive-ajax.min.js",
        "assets/scripts/SharedCode/jquery.redirect.js",
        "assets/scripts/SharedCode/jquery.easing.1.3.js",
        "assets/scripts/SharedCode/newsletterfunctions.js",

        //Bootsrap javascript and plugins
        //"assets/scripts/SharedCode/bootstrap.min.js",
        "assets/scripts/SharedCode/bootstrap/carousel.js",
        "assets/scripts/SharedCode/bootstrap/collapse.js",
        "assets/scripts/SharedCode/bootstrap/transition.js",
        "assets/scripts/SharedCode/bootstrap/tooltip.js",

        "assets/scripts/SharedCode/jquery.validate.min.js",
        "assets/scripts/SharedCode/jquery.validate.unobtrusive.min.js",
        "assets/scripts/SharedCode/animsition.js",
        "assets/scripts/SharedCode/globalfunctions.js",
        "assets/scripts/SharedCode/faqArchiveFunctions.js",
        "assets/scripts/SharedCode/small-box.js",
        "assets/scripts/SharedCode/jquery.mobile.custom.min.js",
        "assets/scripts/SharedCode/image-link-box-carousel.js",
        "assets/scripts/SharedCode/animated-image-link-box.js",
        "assets/scripts/SharedCode/animated-footer.js",
        "assets/scripts/SharedCode/footer/*.js",
        "assets/scripts/SharedCode/footer/*.min.js",
        "assets/scripts/app/footer/*.js",
        "assets/scripts/app/footer/*.min.js"
    ],
    "minify": {
      "enabled": true,
      "preserveImportantComments": true
    }
  }
]

```

**Comment by tajamal** [comment]
![nuget package](https://cloud.githubusercontent.com/assets/1224863/19230582/9f7447bc-8ed5-11e6-884c-7352eb2808b2.PNG)
![nuget update](https://cloud.githubusercontent.com/assets/1224863/19230584/a342e290-8ed5-11e6-95e5-86cedf043a55.PNG)

**Comment by djakaitis** [comment]
I am running into the exact same issue. I do not think there is anything wrong with config (below)

I receive the following error:

`No files matched the pattern wwwroot/js/*.js
`

`// Configure bundling and minification for the project.
// More info at https://go.microsoft.com/fwlink/?LinkId=808241
[
  {
    "outputFileName": "wwwroot/css/site.min.css",
    // An array of relative input file paths. Globbing patterns supported
    "inputFiles": [
      "wwwroot/css/site.css"
    ]
  },
  {
    "outputFileName": "wwwroot/js/site.min.js",
    "inputFiles": [
      "wwwroot/js/site.js",
      "wwwroot/js/*.js"
    ],
    // Optionally specify minification options
    "minify": {
      "enabled": true,
      "renameLocals": true
    },
    // Optinally generate .map file
    "sourceMap": false
  }
]
`

**Comment by djakaitis** [comment]
Was able to resolve by minifying the entire directory: 'wwwroot/js' though this is not exactly ideal.

**Comment by tajamal** [comment]
I discovered every time i merged my nuget package empty folders were deleted and hence that i got and error. I did a workaround and created a dummy file inside each empty folder and no more errors...

**Comment by SCMorgan** [comment]
I'm getting the same issue. 
`"../MyApp/Content/Scripts/*.js"`

gives me an empty bundle. However the following works as expected. 

`"../MyApp/Content/Scripts/"`

It seems that using wildcards anywhere in this route isn't working correctly. Has anybody found a _good_ workaround for the time being?

**Comment by tsauvajon** [comment]
I had the same problem and went from
``` javacript
"inputFiles": [
  "wwwroot/js/*.js"
],
```

to

``` javacript
"inputFiles": [
  "wwwroot/js/"
],
```
and it works fine.

Though, I have the same problem with css files, and 
``` javascript
"inputFiles": [
  "wwroot/css/"
]
```
just doesn't work, for some reason ...

**Comment by flatproject** [comment]
This CSS bundling configuration:
`{
    "outputFileName": "wwwroot/lib/ion-range-slider/css/ion-range-slider.min.css",
    "inputFiles": [
      "wwwroot/lib/ion-range-slider/css/*(*.css|!(*.min.css)"
    ]
  },`

based on this article [https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification#adding-files](url) should work but instead i get the below error when building or cleaning the solution:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "BundlerMinifier.BundlerBuildTask" task failed unexpectedly.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at BundlerMinifier.Bundle.GetAbsoluteInputFiles(Boolean notifyOnPatternMiss)
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable``1 bundles)
   at BundlerMinifier.BundlerBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	PureHub.Mvc	C:\Users\geode\.nuget\packages\buildbundlerminifier\2.4.337\build\BuildBundlerMinifier.targets	18`

Can someone help please?

Also, is there any way to ONLY minify the individual files using a pattern instead of bundling them?

**Comment by tsauvajon** [comment]
What I've done concerning my issues is using another external bundler / minifier (webpack)...

**Comment by Glaicon** [comment]
I had the same problem I solved it so:

 {
    "outputFileName": "wwwroot/bundles/app.js",
    "inputFiles": [
      "wwwroot/**/*.js"
    ],
    "minify": {
      "enabled": true,
      "renameLocals": true
    }
  },
  {
    "outputFileName": "wwwroot/bundles/app.css",
    "inputFiles": [ "wwwroot/**/*.css" ],
    "minify": {
      "enabled": true,
      "renameLocals": true
    }
  },

Good! the two bundles.

But, I have some errors in build solution.

Severity	Code	Description	Project	File	Line	Suppression State
Error	0	Unexpected token, found '@import'	GTX.Presentation.Core
