### ISSUE TITLE
VS 2017 - Enable bundle on build fails

### ISSUE THREAD

**Issue by jkappel71** [madskristensen/BundlerMinifier#234]
### Installed product versions
- Visual Studio: 2017 RC - Professional
- This extension: 2.2.307

### Description
Choosing the "enable bundle on build" option in the context menu of a bundleconfig.json file causes VS to prompt the user about a NuGet package that will be installed to augment the MSBuild process.  It informs you that no files will be added to the project.  When you choose to continue, the install fails and results in the following error:

System.InvalidOperationException: Unable to find version '2.2.307' of package 'BuildBundlerMinifier'.
   at NuGet.PackageManagement.NuGetPackageManager.<GetSourceRepository>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternalAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, Version version, Boolean ignoreDependencies)
   at BundlerMinifierVsix.Commands.BundleOnBuild.<>c__DisplayClass11_1.<EnableCompileOnBuild>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\BundleOnBuild.cs:line 108

### Steps to recreate
1. Right click on the bundleconfig.json file in your project
2. Choose Bundle & Minifier - > Enable bundle on build
3. Accept the dialog to download the NuGet package
4. the above error appears in the output window

**Comment by madskristensen** [comment]
Fixed in v2.3
