### ISSUE TITLE
Visual Studio Getting Crashed with ver# 2.4.340

### ISSUE THREAD

**Issue by jagdish-nasit** [madskristensen/BundlerMinifier#245]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 2.4.340

### Description
Visual studio is getting crashed when we open solution which has bundling & minifier.

Here is Event log:
Faulting application name: devenv.exe, version: 14.0.23107.0, time stamp: 0x559b7ead
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x5736541b
Exception code: 0xe0434352
Fault offset: 0x00014878
Faulting process id: 0x4880
Faulting application start time: 0x01d292bc4625b77b
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 9c25c55a-feaf-11e6-80d3-005056832e52
Faulting package full name: 
Faulting package-relative application ID: 

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerBindingsHelper.ReadBindingsXml(System.String)
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerManager.LoadBindings(Microsoft.VisualStudio.TaskRunnerExplorer.ITaskRunnerAssociatedConfig)
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerManager+<CreateTaskRunnerConfig>d__80.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerManager+<GetTaskRunnerConfigsFromProject>d__79.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerManager+<RefreshProjectConfigs>d__53.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.TaskRunnerExplorer.TaskRunnerSolutionEventsManager+<RunBoundTasksAfterConfigRefresh>d__33.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by madskristensen** [comment]
Can you try the latest release (a few hours old) to see if the problem is fixed?

**Comment by jagdish-nasit** [comment]
I have 2.4.340 installed, seems this is the latest version. I am not getting any update in VS or Site. Am I missing something ? Do we have older version available to use, we are approaching go-live date of our project and this are stuck due to this problem.

**Comment by atkeranov** [comment]
Same here. I have 2.4.340 installed, seems this is the latest version. I am not getting any update in VS.
Every time I update the bundle config JSON, or a file which is included in the bundle, VS stops responding and crashes. This happens only with a large bundle (19 JS files).

**Comment by FabioNascimento** [comment]
Same here...

**Comment by FabioNascimento** [comment]
This crash ocurr with me when I saved files .css, other files working fine.

**Comment by mwgriffiths88** [comment]
I have a the same issue with v2.4.340 which a setup containing:

```
{
    "outputFileName": "Scripts/app/app.min.js",
    "inputFiles": [
      "Scripts/app/datetimepicker.js",
      "Scripts/app/nav-sidebar.js",
      "Scripts/app/validation.js",
      "Scripts/app/dynamic-table.js"
    ]
  }
```

**Comment by jstrugnell** [comment]
Mine crashing too, JavaScript file edits causing VS to freeze until I kill the process. Has anyone got a fix for this?

**Comment by jstrugnell** [comment]
I may have found the issue here. It's at least stopped happening for me. As in mwgriffiths88 case above, I had configured the outputFileName property to include the ".min" extension. Once I removed that part of the filename it stopped crashing, and still generated the file with the ".min" in. 

Hope that helps someone.

**Comment by khaisham** [comment]
**jstrugnell,** I believe that you may have come across a solution for the crash.

A change that I made (which also seemed to work) was that I set the enabled property to false on the minify object. (which then **bundled** my files together (still helpful, but not for performance). 

I had my bundleconfig.json configured the same way **mwgriffiths88** had theirs. (with _".min"_ in the name), so I'm still able to reference the .min.* file in code so that I could keep moving along (in active development on a project).

I added a new config (for new code), set minify.enabled = true and then built... KABLOOEY (that's the sound VS makes when it implodes, right?). After that crash I decided to look to see if anyone had any updates on this problem.  I searched for this last week and wasn't finding anything. I came across your answer this morning and figured I'd try it. 

VIOLA!  No crash. I have built at least 2 dozens times since with no crash. Prior to removing _".min"_ from the name of the file I couldn't build but maybe 1-2 times (if that). ## Just wanted to put it out there that your answer works.

**Comment by jstrugnell** [comment]
Cool, thanks for the confirmation @khaisham. Seems like the package could probably handle this scenario fairly easily, without blowing up. We're obviously not the only people to make the mistake of putting "min" in the output filename.

**Comment by mwgriffiths88** [comment]
@jstrugnell Well spotted, and like @khaisham I can confirm the issue and resolution. I agree with you, it should be able to handle cater for the mistake.

**Comment by dammitjanet** [comment]
This might be the same as #201 - another workaround in there
