### ISSUE TITLE
Null Ref Error when opening html page (open in folder project)

### ISSUE THREAD

**Issue by benaadams** [madskristensen/BundlerMinifier#256]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 2.4.340

### Description

> System.NullReferenceException: Object reference not set to an instance of an object. at BundlerMinifierVsix.AdornmentProvider.CreateAdornments(ITextDocument document, IWpfTextView textView)

### Steps to recreate
Open folder as project (rather than project)
Open html file

Popup about extension failing

Info in ActivityLog.html

> System.NullReferenceException: Object reference not set to an instance of an object. at BundlerMinifierVsix.AdornmentProvider.CreateAdornments(ITextDocument document, IWpfTextView textView) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Adornments\AdornmentProvider.cs:line 85 at BundlerMinifierVsix.AdornmentProvider.TextViewCreated(IWpfTextView textView) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Adornments\AdornmentProvider.cs:line 71 at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<>c__DisplayClass242_0.<BindContentTypeSpecificAssets>b__1() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by pvanaarde** [comment]
Hi, I am experiencing the same problem. Any update on this one?
Thanks, Pieter
