### ISSUE TITLE
NullReferenceException on OnSolutionOpened

### ISSUE THREAD

**Issue by ronhowe** [madskristensen/BundlerMinifier#305]
### Installed product versions
- Visual Studio 2017 Community Edition
- Bundler & Minifier 2.5.359

### Description
Every time I open one of my solutions, I get an exception in the Output window.

### Steps to recreate
1. Open my solution.

### Current behavior
10/16/2017 4:38:19 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifierVsix.ProjectHelpers.GetRootFolder(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:line 68
   at BundlerMinifierVsix.ProjectHelpers.GetConfigFile(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:line 51
   at BundlerMinifierVsix.Commands.ProjectEventCommand.EnsureProjectIsActive(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:line 101
   at BundlerMinifierVsix.Commands.ProjectEventCommand.OnSolutionOpened() in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:line 52

### Expected behavior
No exception raised.  This only started happening relatively recently.  I don't recall if it was a specific update to B&M that started it.

**Comment by s6521d** [comment]
Same problem for me

**Comment by startovernow** [comment]
Same issue here
VS Enterprise 2017 version 15.6.4
Bundler & Minifier 2.5.359
