### ISSUE TITLE
Object reference not set to an instance of an object if folder name have .js

### ISSUE THREAD

**Issue by grifin85** [madskristensen/BundlerMinifier#322]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 2.5.359

### Description

```
24.12.2017 21:30:08: System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.FileHelpers.NormalizePath(String path) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Helpers\FileHelpers.cs:line 84
   at BundlerMinifier.Bundle.GetAbsoluteOutputFile() in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\Bundle.cs:line 62
   at BundlerMinifier.BundleFileProcessor.OnProcessing(Bundle bundle, String baseFolder) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 196
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 101
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 40
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass8_0.<Process>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 112
24.12.2017 21:30:20: System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.FileHelpers.NormalizePath(String path) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Helpers\FileHelpers.cs:line 84
   at BundlerMinifier.Bundle.GetAbsoluteOutputFile() in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\Bundle.cs:line 62
   at BundlerMinifier.BundleFileProcessor.OnProcessing(Bundle bundle, String baseFolder) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 196
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 101
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles) in C:\projects\bundlerminifier\src\BundlerMinifier.Core\Bundle\BundleFileProcessor.cs:line 40
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass8_0.<Process>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 112
```

### Steps to recreate
Try add "node_modules/popper.js/dist/popper.min.js"

**Comment by coultonluke** [comment]
Also getting this issue when packaging up the following script provided by Microsoft for SignalR:

"node_modules/@aspnet/signalr-client/dist/browser/signalr-clientES5-1.0.0-alpha2-final.js",

Here's what my package section looks like for it:

![image](https://user-images.githubusercontent.com/16463338/34641093-8e4c517e-f2f6-11e7-9f8f-ed589843dae3.png)

**Comment by sonsy-soft** [comment]
I have this error ,
there is no solution,is there ?

**Comment by Vasanthvivi** [comment]
i am also getting this kind of error while bundling all of the angular production build files,,

**Comment by Vasanthvivi** [comment]
i think this is just copying all the contents together in a certain way,, when we use ''this'' keyword context will be differ i think....
