### ISSUE TITLE
As soon as Bundle Project is ran, exception within VS and non-responsive

### ISSUE THREAD

**Issue by cropper1991** [madskristensen/BundlerMinifier#349]
### Installed product versions
- Visual Studio:2015 Professional
- This extension: 2.6.375

### Description
When opening my Visual Studio 2015 this morning I was notified that there is a new version of this extension. So I subsequently updated it to 2.6.375.

Once building our solution(s) and it encounters the Bundler Minfier Config file, Visual Studio subsequently crashes.

Stack Trace: 
Exception Info: System.InvalidOperationException
   at Microsoft.VisualStudio.Shell.AsyncPackage.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.Package.System.IServiceProvider.GetService(System.Type)
   at Microsoft.VisualStudio.Shell.VsShellUtilities.ShowMessageBox(System.IServiceProvider, System.String, System.String, Microsoft.VisualStudio.Shell.Interop.OLEMSGICON, Microsoft.VisualStudio.Shell.Interop.OLEMSGBUTTON, Microsoft.VisualStudio.Shell.Interop.OLEMSGDEFBUTTON)
   at BundlerMinifierVsix.BundleService.HandleProcessingException(System.String, System.Exception)
   at BundlerMinifierVsix.BundleService+<>c__DisplayClass11_0.<SourceFileChanged>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### Steps to recreate
Update to the latest available version of this extension, re-build any solution which contains bundler minifier config, you should then encounter the error.

### Current behavior
Making visual studio both crash and unresponsive, preventing building of solution which contains bundler minifier config file. 

### Expected behavior
Should build as expected with no crash.

**Comment by mbelchuke** [comment]
We're experiencing the same problem as well. 

Visual Studio:2017 Professional

**Comment by henrypiassek** [comment]
Same here. I don't run on build but do it manually instead. I'm getting an error message (about Newtonsoft.Json version 9.0.0.0 assembly not being found) from within task runner explorer when trying to execute minifier tasks. 

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at BundlerMinifier.BundleHandler.TryGetBundles(String configFile, IEnumerable`1& bundles)
   at BundlerMinifierConsole.Program.GetConfigFileFromArgs(String[] args, String& configPath)
   at BundlerMinifierConsole.Program.Main(String[] args)

Tried to fully uninstall / install the extension again but that didn't help either...

**Comment by henrypiassek** [comment]
Just a quick heads up:

I was able to solve my issues temporarily by manually copying (don't try this at home!) the Newtonsoft.Json assembly (version 9.0.1) to the extension directory (somewhere inside AppData\Local\...)

Had to get it working urgently so I can live with that for now. Maybe this will help you as well even though you seem to experience another issue.

**Comment by Roamel** [comment]
It looks like the same bug: https://github.com/madskristensen/BundlerMinifier/issues/329

**Comment by cropper1991** [comment]
In my case it's not, I'm getting completely different error message Roamel.

**Comment by madskristensen** [comment]
I think I have a fix. Can you please try [this build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/) and see if that works in VS2015?

**Comment by cropper1991** [comment]
Unfortunately, the build you've pointed me to still exhibits the same behaviour. I didn't think I was hitting issues relating to NewtonSoft JSON libraries.

**Comment by madskristensen** [comment]
@cropper1991 Yeah, I see it now too. It's a weird version conflict since VS 2015 ships with an older version of JSON.NET

**Comment by madskristensen** [comment]
Ok, latest version (2.6.377) seems to work

**Comment by cropper1991** [comment]
Okay will test and come back to you with my findings.

**Comment by mbelchuke** [comment]
2.6.378 seems to work for VS2017 as well.

**Comment by cropper1991** [comment]
2.6.378 version fixes the issue for me.

**Comment by Thijmen** [comment]
Unfortunately, 2.6.378 causes VS15 and VS17 to crash when I try to bundle my files.

**Comment by Roamel** [comment]
Hi @Thijmen. It would be better to create a new bug with detailed step to reproduce, because this one is closed.
