### ISSUE TITLE
Throws System.NullReferenceException when loading a Business Intelligence Integration Services project

### ISSUE THREAD

**Issue by mh-charlie-gillis** [madskristensen/BundlerMinifier#350]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 2.6.378

### Description
Throws System.NullReferenceException when loading a Business Intelligence Integration Services project, which has no web-related assets/artifacts.

### Steps to recreate
Open an existing Business Intelligence Integration Services project

### Current behavior
Throws exception:
4/10/2018 2:15:58 PM: System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifierVsix.ProjectHelpers.GetRootFolder(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:line 68
   at BundlerMinifierVsix.ProjectHelpers.GetConfigFile(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:line 51
   at BundlerMinifierVsix.Commands.ProjectEventCommand.EnsureProjectIsActive(Project project) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:line 102
   at BundlerMinifierVsix.Commands.ProjectEventCommand.OnSolutionOpened() in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:line 53

### Expected behavior
Ignore this project type

**Comment by lepipele** [comment]
Can you please provide example solution in ZIP file that breaks on your machine and upload it here so I can test? To me it seems that null check / `NullReferenceException` catch here would solve the issue:

https://github.com/madskristensen/BundlerMinifier/blob/856cee64e1943426024f58c4eb9a80626439dcd8/src/BundlerMinifierVsix/Helpers/ProjectHelpers.cs#L68

But I want to test before deploying new version.

**Comment by mh-charlie-gillis** [comment]
Sure
[Integration Services Project1.zip](https://github.com/madskristensen/BundlerMinifier/files/1899808/Integration.Services.Project1.zip)

**Comment by lepipele** [comment]
Fixed in commit referenced and tested, works now. Be on a lookout for new version of `vsix`, or:

1. download repository and compile VSIX for yourself ;)
2. try using NuGet in project instead of extension

@madskristensen you OK with direct commits or you prefer me to issue pull requests and wait your reviews?
