### ISSUE TITLE
Using globbing patterns: "System.ArgumentException: Illegal characters in path."

### ISSUE THREAD

**Issue by aureole82** [madskristensen/BundlerMinifier#383]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2017 Version 15.8.4
- This extension: 2.8.396

### Description
Globbing pattern from [documentation](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x#add-files-to-workflow) doesn't work.

### Steps to recreate
bundleconfig.json:

    {
      "inputFiles": ["wwwroot/js/**/*(*.js|!(*.min.js))"],
      "outputFileName": "wwwroot/js/app.min.js"
    }

### Current behavior
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at BundlerMinifier.Bundle.GetAbsoluteInputFiles(Boolean notifyOnPatternMiss)
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
   at BundlerMinifierVsix.BundleService.<>c__DisplayClass8_0.<Process>b__0(Object o) in C:\projects\bundlerminifier\src\BundlerMinifierVSIX\BundleService.cs:line 112

**Comment by killnine** [comment]
+1 I'm having this same issue.

**Comment by rodrigosoreis** [comment]
+1 I'm having this same issue.

**Comment by andreeag3191** [comment]
+1

**Comment by mganss** [comment]
This is due to 
https://github.com/madskristensen/BundlerMinifier/blob/e043b29f40a3778ae189bba1cdb9c30c5b72dcb6/src/BundlerMinifier.Core/Bundle/Bundle.cs#L78 https://github.com/madskristensen/BundlerMinifier/blob/e043b29f40a3778ae189bba1cdb9c30c5b72dcb6/src/BundlerMinifier.Core/Bundle/Bundle.cs#L97

I'd  drop the `+ ext` part and remove `ext` var, globbing wil take care of filtering the input files. 

Also, I don't see a way around enumerating all files from the folder where `bundleconfig.json` is located downward. It's the price you have to pay when using a glob library that doesn't do file traversal (unlike, say, https://github.com/mganss/Glob.cs 😉). If you only remove the `ext` you'll run into another issue because of https://github.com/madskristensen/BundlerMinifier/blob/e043b29f40a3778ae189bba1cdb9c30c5b72dcb6/src/BundlerMinifier.Core/Bundle/Bundle.cs#L88
which doesn't take into account cases where the glob pattern spans directories (like `**`).

A possible duplicate is #192. The same issue is https://github.com/aspnet/AspNetCore.Docs/issues/9474

Please let me know if I should make a PR.

**Comment by tbebekis** [comment]
I just downloaded the latest version and the problem unfortunately remains. Can't use globbing patterns.
