### ISSUE TITLE
Illegal characters error in CssRelativePathAdjuster

### ISSUE THREAD

**Issue by leonex** [madskristensen/BundlerMinifier#434]
### Installed product versions
- Visual Studio: 2019
- This extension: 2.9.406

### Description
Error in CssRelativePath.Adjust function in "BundlerMinifier/src/BundlerMinifier.Core/Minify/CssRelativePathAdjuster.cs"

### Steps to recreate
1. Add "jquery-ui.css" to input files in bundle config
` "inputFiles": [
      "wwwroot/libs/jquery-ui/jquery-ui.css"
]
`

[https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css](https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css)

2. Begin processing bundleconfig.json
3. Error will be throw:

> Error MSB4018 The "BundlerMinifier.BundlerBuildTask" task failed unexpectedly. 
   System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at BundlerMinifier.CssRelativePath.Adjust(String inputFile, String outputPath)
   at BundlerMinifier.BundleHandler.ProcessBundle(String baseFolder, Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
   at BundlerMinifier.BundlerBuildTask.Execute()

### Current behavior
RegEx `url\s*\(\s*([""']?)([^:<)]+)\1\s*\)` match `url(%22images%2Fui-icons_555555_256x240.png%22)` in file comments, and can't replace path with specific character in `Path.Combine`

### Expected behavior
1. Ignore regex in comments
2. Decode path

**Comment by mykola-kohut** [comment]
Is there a solution for this?

**Comment by Vitaly9354** [comment]
Same issue. We have special custom variables in our css paths like
`backgound: url(PATH|image_dir|hands.png)`
and build fails in the same way.
