### ISSUE TITLE
Thread rule violation in BundlerMinifier

### ISSUE THREAD

**Issue by lifengl** [madskristensen/BundlerMinifier#437]
Turn on trace logging, and those exceptions can be found in the log:

This operation should only take place on the UI thread.

	Stack Trace:
		VerifyOnUIThread at offset 252 in file:line:column <filename unknown>:0:0
		NotifyPropertySinks at offset 55 in file:line:column <filename unknown>:0:0
		Update at offset 107 in file:line:column <filename unknown>:0:0
		GetNodeProperties at offset 373 in file:line:column <filename unknown>:0:0
		Create at offset 59 in file:line:column <filename unknown>:0:0
		get_Properties at offset 40 in file:line:column <filename unknown>:0:0
		GetRootFolder at offset 36 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:62:13
		GetConfigFile at offset 9 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:51:13
		FileChanged at offset 181 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:141:17
		OnRenamed at offset 145 in file:line:column <filename unknown>:0:0
		NotifyRenameEventArgs at off...

**Comment by saluton-mundo** [comment]
Hi @madskristensen and team,

Encountering an issue when publishing a  <TargetFramework>netcoreapp2.2</TargetFramework> project to folder:

=====================
22/08/2019 15:18:42
LimitedFunctionality
System.Runtime.InteropServices.COMException (0x8001010E): This operation should only take place on the UI thread. at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.VerifyOnUIThread()

	Stack Trace:
		VerifyOnUIThread at offset 253 in file:line:column <filename unknown>:0:0
		NotifyPropertySinks at offset 55 in file:line:column <filename unknown>:0:0
		Update at offset 107 in file:line:column <filename unknown>:0:0
		GetNodeProperties at offset 374 in file:line:column <filename unknown>:0:0
		Create at offset 59 in file:line:column <filename unknown>:0:0
		get_Properties at offset 40 in file:line:column <filename unknown>:0:0
		GetRootFolder at offset 36 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:62:13
		GetConfigFile at offset 9 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:51:13
		FileChanged at offset 181 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:141:17
		OnChanged at offset 48 in file:line:column <filename unknown>:0:0
		NotifyFileSystemEventArgs at offset 84 in file:line:column <filename unknown>:0:0
		CompletionStatusChanged at offset 351 in file:line:column <filename unknown>:0:0
		PerformIOCompletionCallback at offset 135 in file:line:column <filename unknown>:0:0
===================

In addition, there also errors present with WebCompiler:

`22/08/2019 15:30:27: Error getting the active projectSystem.ArgumentException: Value does not fall within the expected range.
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in 
   at EnvDTE80.DTE2.get_ActiveDocument()
   at WebCompilerVsix.ProjectHelpers.GetActiveProject() in C:\projects\webcompiler\src\WebCompilerVsix\Helpers\ProjectHelpers.cs:line 227`

The publish is targeting Release on linux-x64 as Self-Contained.

**Comment by mm98** [comment]
I can confirm, that the same error happens for me:
```

=====================
24-09-2019 08:04:55
LimitedFunctionality
System.Runtime.InteropServices.COMException (0x8001010E): This operation should only take place on the UI thread.

	Stack Trace:
		VerifyOnUIThread at offset 252 in file:line:column <filename unknown>:0:0
		NotifyPropertySinks at offset 55 in file:line:column <filename unknown>:0:0
		Update at offset 107 in file:line:column <filename unknown>:0:0
		GetNodeProperties at offset 373 in file:line:column <filename unknown>:0:0
		Create at offset 59 in file:line:column <filename unknown>:0:0
		get_Properties at offset 40 in file:line:column <filename unknown>:0:0
		GetRootFolder at offset 36 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:62:13
		<FileChanged>b__0 at offset 17 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:139:67
		FirstOrDefault<TSource> at offset 151 in file:line:column <filename unknown>:0:0
		FileChanged at offset 170 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:141:17
		OnChanged at offset 49 in file:line:column <filename unknown>:0:0
		NotifyFileSystemEventArgs at offset 83 in file:line:column <filename unknown>:0:0
		CompletionStatusChanged at offset 335 in file:line:column <filename unknown>:0:0
		PerformIOCompletionCallback at offset 141 in file:line:column <filename unknown>:0:0

   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.VerifyOnUIThread()
===================
```

**Comment by jaldrin** [comment]
I am also encountering this problem in VS 2019 - Version 16.5.0 on a netcoreapp3.1 project when doing a build.

```
=====================
3/23/2020 12:11:59 PM
LimitedFunctionality
System.Runtime.InteropServices.COMException (0x8001010E): This operation should only take place on the UI thread.

	Stack Trace:
		VerifyOnUIThread at offset 68 in file:line:column <filename unknown>:0:0
		NotifyPropertySinks at offset 55 in file:line:column <filename unknown>:0:0
		Update at offset 107 in file:line:column <filename unknown>:0:0
		GetNodeProperties at offset 373 in file:line:column <filename unknown>:0:0
		Create at offset 59 in file:line:column <filename unknown>:0:0
		get_Properties at offset 40 in file:line:column <filename unknown>:0:0
		GetRootFolder at offset 36 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Helpers\ProjectHelpers.cs:62:13
		<FileChanged>b__0 at offset 17 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:139:67
		FirstOrDefault<TSource> at offset 151 in file:line:column <filename unknown>:0:0
		FileChanged at offset 170 in file:line:column C:\projects\bundlerminifier\src\BundlerMinifierVSIX\Commands\ProjectEventCommand.cs:141:17
		OnChanged at offset 49 in file:line:column <filename unknown>:0:0
		NotifyFileSystemEventArgs at offset 83 in file:line:column <filename unknown>:0:0
		CompletionStatusChanged at offset 335 in file:line:column <filename unknown>:0:0
		PerformIOCompletionCallback at offset 141 in file:line:column <filename unknown>:0:0

   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.VerifyOnUIThread()
===================

```
