### ISSUE TITLE
Error installing in Visual Studio 2019

### ISSUE THREAD

**Issue by jtsom** [madskristensen/BundlerMinifier#458]
### Installed product versions
- Visual Studio: 2019 Enterprise Version 16.5.0 Preview 1.0
- This extension: v3.2.435

### Description
NullReferenceException when trying to install package. This is on a new AspNet Core 3.1 Razor pages project.

### Steps to recreate
Right click on Manage NuGet Packages
Search for BuildBundlerMinifier
Click install button

### Current behavior
Package does not install, errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "BundlerMinifier.BundlerBuildTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
   at BundlerMinifier.BundlerBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AcademyWeb	C:\Users\John Tsombakos\.nuget\packages\buildbundlerminifier\3.2.435\build\BuildBundlerMinifier.targets	12	

```

### Expected behavior
Package is installed without error.

**Comment by UM001** [comment]
Same error here. I read here that it should work natively in Visual Studio:
https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1

Is this true? I did not get it to work....

My error (next to exclamation that package is most likely wrong and not matching .net core 3.1:

\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018: The "BundlerMinifier.BundlerBuildTask" task failed unexpectedly.
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018: System.ArgumentException: Illegal characters in path.
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at System.IO.Path.GetExtension(String path)
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at BundlerMinifier.Bundle.GetAbsoluteInputFiles(Boolean notifyOnPatternMiss)
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at BundlerMinifier.BundlerBuildTask.Execute()
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
\buildbundlerminifier\3.2.449\build\BuildBundlerMinifier.targets(12,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()`
`

**Comment by UM001** [comment]
The issue with the exclamation in the packages is still there. It runs if you do not use the * astrix of the global pattern as given in this visual studio magazine, but just add the files.
https://visualstudiomagazine.com/blogs/tool-tracker/2018/12/bundling-scripts.aspx
