### ISSUE TITLE
Error executing task "BundlerMinifier.BundlerBuildTask" -- FAILED.

### ISSUE THREAD

**Issue by rdaddinsc** [madskristensen/BundlerMinifier#481]
### Installed product versions
VS 2019 build tools (v16.5.4)
v3.2.447

### Description
We are trying to build using CI steps. 
We call Dot Net Core task with (build E:\Agent-1\_work\39\s\Test\Test\Test.Web.csproj --configuration Release --output $(build.artifactstagingdirectory)\Test )  
We run into this build error 4 out of 5 times.  

If we do not Include="BuildBundlerMinifier" it does not process minifcation. 

Note: We currently have bundleconfig.json.bindings included which has content produceoutput=true 

### Steps to recreate
See Description section

### Build Error
2020-04-27T17:34:05.4563613Z    1:7>Target "BundleMinify" in file "C:\Users\tfsbuild\.nuget\packages\buildbundlerminifier\3.2.447\build\BuildBundlerMinifier.targets" from project "E:\Agent-1\_work\39\s\Test\Test\Test.Web.csproj" (target "BeforeCompile" depends on it):
2020-04-27T17:34:05.4563916Z        Using "BundlerMinifier.BundlerBuildTask" task from assembly "C:\Users\tfsbuild\.nuget\packages\buildbundlerminifier\3.2.447\build\..\tools\netstandard1.3\BundlerMinifier.dll".
2020-04-27T17:34:05.4564160Z        Task "BundlerMinifier.BundlerBuildTask"
2020-04-27T17:34:05.4564361Z          
2020-04-27T17:34:05.4564541Z          Bundler: Begin processing bundleconfig.json
2020-04-27T17:34:05.4581570Z          	Bundled wwwroot/js/settingsjs.js
2020-04-27T17:34:05.6868617Z        Done executing task "BundlerMinifier.BundlerBuildTask" -- FAILED.
2020-04-27T17:34:05.6876218Z    1:7>Done Building Project "E:\Agent-1\_work\39\s\Test\Test\Test.Web.csproj" (default targets) -- FAILED.
2020-04-27T17:34:05.7010184Z 
2020-04-27T17:34:05.7010546Z Build FAILED.
2020-04-27T17:34:05.7010712Z     0 Warning(s)
2020-04-27T17:34:05.7010800Z     0 Error(s)
2020-04-27T17:34:05.7011108Z 
2020-04-27T17:34:05.7011196Z Time Elapsed 00:00:18.84
2020-04-27T17:34:05.7115889Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2020-04-27T17:34:05.7116862Z Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 213 should have been in the ID-to-project file mapping but wasn't!
2020-04-27T17:34:05.7117150Z    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
2020-04-27T17:34:05.7117390Z    at Microsoft.Build.BackEnd.Logging.LoggingService.GetAndVerifyProjectFileFromContext(BuildEventContext context)
2020-04-27T17:34:05.7117619Z    at Microsoft.Build.BackEnd.Logging.LoggingService.LogBuildEvent(BuildEventArgs buildEvent)
2020-04-27T17:34:05.7117849Z    at Microsoft.Build.BackEnd.TaskHost.LogErrorEvent(BuildErrorEventArgs e)
2020-04-27T17:34:05.7118118Z    at Microsoft.Build.Utilities.TaskLoggingHelper.LogError(String subcategory, String errorCode, String helpKeyword, String file, Int32 lineNumber, Int32 columnNumber, Int32 endLineNumber, Int32 endColumnNumber, String message, Object[] messageArgs)
2020-04-27T17:34:05.7118460Z    at BundlerMinifier.BundlerBuildTask.BundleMinifier_ErrorMinifyingFile(Object sender, MinifyFileEventArgs e)
2020-04-27T17:34:05.7118690Z    at BundlerMinifier.BundleMinifier.OnErrorMinifyingFile(MinificationResult result)
2020-04-27T17:34:05.7118905Z    at BundlerMinifier.BundleMinifier.MinifyBundle(Bundle bundle)
2020-04-27T17:34:05.7119120Z    at BundlerMinifier.BundleFileProcessor.ProcessBundle(String baseFolder, Bundle bundle)
2020-04-27T17:34:05.7119335Z    at BundlerMinifier.BundleFileProcessor.Process(String fileName, IEnumerable`1 bundles)
2020-04-27T17:34:05.7119550Z    at BundlerMinifier.BundlerBuildTask.Execute()
2020-04-27T17:34:05.7119755Z    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2020-04-27T17:34:05.7120034Z    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
2020-04-27T17:34:05.7120586Z    at Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(TaskLoggingContext taskLoggingContext, ItemBucket bucket, IDictionary`2 taskIdentityParameters, TaskHost taskHost, TaskExecutionMode howToExecuteTask)
2020-04-27T17:34:05.7120860Z    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask, Dictionary`2 lookupHash)
2020-04-27T17:34:05.7121109Z    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TaskExecutionMode mode, Lookup lookup)
2020-04-27T17:34:05.7121407Z    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(TargetLoggingContext loggingContext, BuildRequestEntry requestEntry, ITargetBuilderCallback targetBuilderCallback, ProjectTargetInstanceChild taskInstance, TaskExecutionMode mode, Lookup inferLookup, Lookup executeLookup, CancellationToken cancellationToken)
2020-04-27T17:34:05.7121759Z    at Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(ITaskBuilder taskBuilder, TargetLoggingContext targetLoggingContext, TaskExecutionMode mode, Lookup lookupForInference, Lookup lookupForExecution)
2020-04-27T17:34:05.7122101Z    at Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(ITaskBuilder taskBuilder, BuildRequestEntry requestEntry, ProjectLoggingContext projectLoggingContext, CancellationToken cancellationToken)
2020-04-27T17:34:05.7122365Z    at Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(ITaskBuilder taskBuilder)
2020-04-27T17:34:05.7122649Z    at Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(ProjectLoggingContext loggingContext, BuildRequestEntry entry, IRequestBuilderCallback callback, String[] targetNames, Lookup baseLookup, CancellationToken cancellationToken)
2020-04-27T17:34:05.7122893Z    at Microsoft.Build.BackEnd.RequestBuilder.BuildProject()
2020-04-27T17:34:05.7123132Z    at Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()
2020-04-27T17:34:05.7123470Z    at Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(Boolean setThreadParameters)
2020-04-27T17:34:05.7123636Z 
2020-04-27T17:34:05.7123841Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2020-04-27T17:34:05.7124076Z Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 213 should have been in the ID-to-project file mapping but wasn't!
2020-04-27T17:34:05.7124550Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
2020-04-27T17:34:05.7124941Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2020-04-27T17:34:05.7311771Z Unhandled exception. Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: ContextID 213 should have been in the ID-to-project file mapping but wasn't!
2020-04-27T17:34:05.7338756Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
2020-04-27T17:34:05.7366273Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
2020-04-27T17:34:05.7368658Z    at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
2020-04-27T17:34:05.9646517Z ##[debug]rc:255
2020-04-27T17:34:05.9647255Z ##[debug]success:false
2020-04-27T17:34:05.9711694Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 255
2020-04-27T17:34:05.9720741Z ##[debug]Processed: ##vso[task.issue type=error;]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 255
2020-04-27T17:34:05.9721230Z ##[debug]task result: Failed
2020-04-27T17:34:05.9721621Z ##[error]Dotnet command failed with non-zero exit code on the following projects : E:\Agent-1\_work\39\s\Test\Test\Test.csproj
2020-04-27T17:34:05.9722105Z ##[debug]Processed: ##vso[task.issue type=error;]Dotnet command failed with non-zero exit code on the following projects : E:\Agent-1\_work\39\s\Test\Test\Test.Web.csproj
2020-04-27T17:34:05.9739436Z ##[debug]Processed: ##vso[task.complete result=Failed;]Dotnet command failed with non-zero exit code on the following projects : E:\Agent-1\_work\39\s\Test\Test\Test.Web.csproj
2020-04-27T17:34:05.9810209Z ##[section]Finishing: Test build

### Current behavior
We are trying to build using CI steps. 
We run into this build errors 4 out of 5 times.  

### Expected behavior
It should build without any build errors.

**Comment by karan-kang** [comment]
We are facing the same issue with dotnet publish .netcore 3.1 as well in CI build environment

**Comment by rwasef1830** [comment]
I faced this as well, I ended up repackaging the command line bundler into a dotnet tool and just calling that using <Exec> It's already a command line application.

**Comment by karan-kang** [comment]
> I faced this as well, I ended up repackaging the command line bundler into a dotnet tool and just calling that using `<Exec>` It's already a command line application.

Can you please post how you did this?

**Comment by rwasef1830** [comment]
Checkout this repo, then run this in a cmd in the repo:

```
dotnet pack src\BundlerMinifier.Core /p:PackAsTool=true /p:ToolCommandName=bundle /p:PackageId=BundlerMinifier.Core.Tool /p:Version=3.3 --output .publish -c Release /p:TargetFrameworks=netcoreapp3.1
```

That will make a nuget package in .publish, then use a NuGet.config in your solution folder to add a custom nuget source (point to a folder containing this package), then `dotnet tool add bundle`
