### ISSUE TITLE
Exception when hitting an exception in JS code opens a dynamic source file

### ISSUE THREAD

**Issue by KernelLeak** [madskristensen/BundlerMinifier#99]
When a JavaScript exception in IE triggers opening the matching dynamic source file in VS 2015 I now get the following error in ActivityLog.xml:

```
System.Runtime.InteropServices.COMException (0x80020003): Member not found. (Exception from HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND)) 
at EnvDTE.SolutionClass.FindProjectItem(String FileName)
at BundlerMinifierVsix.AdornmentProvider.CreateAdornments(ITextDocument document, IWpfTextView textView) in C:\projects\bundlerminifier\src\BundlerMinifierVsix\Adornments\AdornmentProvider.cs:line 84
at BundlerMinifierVsix.AdornmentProvider.TextViewCreated(IWpfTextView textView) in C:\projects\bundlerminifier\src\BundlerMinifierVsix\Adornments\AdornmentProvider.cs:line 70
at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.<>c__DisplayClass241_0.<BindContentTypeSpecificAssets>b__1()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
```

The source file it is showing is called "Function code [dynamic]".

**Comment by KernelLeak** [comment]
I also just got the exact same exception when I was setting a breakpoint in a dynamic JavaScript file.
